### ISSUE TITLE
Unable to use on any file: "longnameresult is undefined"

### ISSUE THREAD

**Issue by nchachereau** [robamler/dontprint#30]
Hi there! I like the idea very much, and had been looking for such a tool. I was glad when I stumbled upon your post on the Zotero forums. Unfortunately it does not work for me right now.

Whenever I try to use Dontprint on a PDF (whether through the icon in the address bar, through the "Send local PDF document to e-reader" or through the button in Zotero), I get the following error:

> Error message: 	TypeError: longnameresult is undefined
> Operation: 	cropping

I am using Ubuntu 15.04 and Firefox 39. I downloaded k2pdfopt through Dontprint, which successfully put the program to the dontprint folder in my Firefox profile. I have been able to use this k2pdfopt executable on the command line, so the problem definitely lies in Dontprint itself.

(I'm willing to help debugging this: do not hesitate to tell me any additional information you need or give me pointers to where the problem might lie.)

**Comment by robamler** [comment]
Wow, thanks a lot for reporting this! This was due to a bug introduced in commit c444ac9 and it affected everybody who downloaded version 1.0.1 of Dontprint from the website. Unfortunately, the bug did *not* affect anyone who updated to version 1.0.1 from an earlier version, which is why I didn't spot it myself.

Could you please try the following and let me know if Dontprint now works for you:

1. Enter "about:addons" in the Firefox address bar and hit enter.
2. Go to the "Extensions" tab (second one from the top), left-click on "Dontprint" to select it, then right-click on it and choose "Find updates" from the context menu.
3. Wait for the update to version 1.0.2 to download.
4. Restart Firefox and try using Dontprint.

If it still doesn't work, please don't hesitate to reopen this bug. Otherwise, I would appreciate a brief confirmation that this update fixes your issue.

**Comment by robamler** [comment]
And thanks for your offer to debug this yourself! It just turned out that the source of this bug was rather obvious once I was aware of the problem.

**Comment by nchachereau** [comment]
Hi! Thanks a lot, this fixes it for me! (The update had been downloaded automatically by the time I saw your message. I didn't try to do a fresh install. In case that changes anything.)

I now had the chance to use Dontprint, and I have to say, the GUI for cropping looks great! I'll definitely use it a lot in the next weeks and will report any problems I see, and hopefully submit crop settings for a few journals in my field.

**Comment by robamler** [comment]
Perfect! Bug reports are always welcome.
