### ISSUE TITLE
Renaming output file pre-send

### ISSUE THREAD

**Issue by emallson** [robamler/dontprint#34]
Currently, the format that Dontprint uses for output is one of two things:

1. `<input name>`, when it cannot get metadata from Zotero, or
2. `<first author last name>, <title>`, when it can get metadata

When a paper is only available as a raw PDF, Zotero cannot get metadata (or Dontprint doesn't use it). I run into this problem frequently with USENIX Security Symposium papers, which are hosted on their website as raw PDFs without additional metadata.

It would be nice if we could change the name of the output manually without having to connect the Kindle to a PC after receiving the file.

It would also be nice if it were possible to change the default with-metadata format (to `<first author last name> <year>, <title>`, for example).

I may be able to implement these changes myself (time being the only issue).

**Comment by robamler** [comment]
Thanks for the suggestions! Depending on your e-reader model, the name that will be displayed on your e-reader for a given document depends on a combination of
* the document's file name
* some meta data fields in the PDF document, such as the "title" and "author" field.

Kindle e-readers seem to ignore the "title" meta data and display only the file name followed by the author, if it is set. Other e-readers ignore the file name and display only the contents of the "title" meta data field if it is set.

In the above commit, I implemented the following changes, which affect only the output file name and not the meta data fields:

* By default, the output file is now named either
    * "&lt;first autor last name&gt; (&lt;year>), &lt;title&gt;.pdf" or
    * "&lt;first autor last name&gt;, &lt;title&gt;.pdf" or
    * "&lt;title&gt;.pdf",

    depending on which meta data is available.

* On the cropping tab, there is now an input box where the user can    override the default output file name (see screenshot below). This tab is always displayed if Dontprint cannot find enough meta data for the article in order to pick the crop settings automatically. Thus, for the raw PDF files that you mentioned, this change should allow you to set the output file name.

I'm not so sure whether an input box for the file name is really the right way to go, since the file name is not displayed on all e-reader models. Maybe it would be better to have an input box where the user can override the document title manually, and the file name is then composed automatically from title, author, and year. What do you think?

![image](https://cloud.githubusercontent.com/assets/1719283/14066631/5d4d97e2-f44f-11e5-84e2-0cd91284a8a1.png)

**Comment by emallson** [comment]
I like the idea of being able to override the title manually instead of just the filename. Since one of the cases is `<title>.pdf` that would allow users to override the entire filename if no metadata were available. So it would cover my case (kindle displays filename instead of title for PDFs) as well as other cases where it shows the title instead.

This has me thinking that it'd be nice to be able to set the author field as well, but one thing at a time.

**Comment by robamler** [comment]
This will be available in the next version. I decided to let the user set only the article title but not the author field for two reasons. First, the cropping tab probably already looks kind of overwhelming to first-time users as it is now. Second, while all users will see the title of the converted PDF in some way or another (either directly or because the file name of the generated PDF will contain the title), depending on your e-reader model, you might never see the contents of the "author" meta data field. It would be very confusing to let users set an "author" string which is never displayed back to them.
